language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
not:
  secure: Z1S1bHUC1QmFOkPZgfUlMJOGMOkA75jyPcwEhOkIqrOobt0ZAUOjTZqxCDnfST/OCTAr3quPjehF75Yd9mvNNlaDXcdFPS2JBZyNdqc5aajonf4v+4YOOLN1x9ue6WSTNMoOPp6C/Btat3zW0+o3uf9TMVlVBIkqgJYeyItPBXnYhm2u1+70wDDHV9GDvR29k66GCEu4XNY6SZ9lJgLg9Cl7p1uxdbE+Kyh7qQeFnFCFDSKgUmyGxD9oYnEb03KgClGkAXozkQ9ybmYDoQbEUiWP2hFnT+0A4OQ4fOyOXI9gwNVaYUf/xDUGrO7S30QxP/Ajt0V6nqyV5oWmrn5QReONo6esnFR0kPCkArASI877hDt8DzpAzIrsIlbhSDrCutpKmq5DtneSVENC0ZaowQg4ChN8bA54HGcRxmqpIzSW2VwKaO6y18l/9gj3EYlDbGNAhexjjkoRDqBivAcJybXiC196QnmDtcGe4mcWGKVuxTN5Uk2sxxOq1XKUqqfRYClSIefzjYS1POqhe0zP1+9GnAqRE22QS3+j93GKFdKFhwuK+WiE6QCuQ5zFe7dL4KQ2qWFTJJx4umefU3sqRlMdyf2pD2vg7nSRml0Y8/K+XuFd4Ixm1QQfjrSHVfcrCjWCypVS04Shjj+Ejgez5XIjE0dE77SJOfY5mn6Ekbk=
